#!/usr/bin/env node
/**
 * Resolves restaurant NAMES to menu URLs via Google Places, then writes them
 * into menu-test-urls.txt so the test harness has real data to chew on.
 *
 * For each name:
 *   1. Google Places "find place from text" → place_id
 *   2. Place details → website URL (homepage)
 *   3. Emits 3 URL candidates per restaurant: the homepage, homepage/menu,
 *      homepage/menus. The test harness will try each and the per-row output
 *      shows which path actually parses. (Most restaurants put menus at
 *      /menu or /menus, but some serve them on the homepage.)
 *
 * Requires GOOGLE_PLACES_API_KEY. The server already has it on Render; for
 * local runs set it in server/.env.
 *
 * Usage:
 *   # Use the bundled Chicago seed list:
 *   node server/scripts/seedMenuTestUrls.js
 *
 *   # Or pass your own names (file or inline):
 *   node server/scripts/seedMenuTestUrls.js my-restaurants.txt
 *   node server/scripts/seedMenuTestUrls.js "Lou Malnati's" "Au Cheval" "Pequod's"
 *
 * Writes to: server/scripts/menu-test-urls.txt (overwrites)
 */

require('dotenv').config({ path: require('path').resolve(__dirname, '..', '.env') });

const fs = require('fs');
const path = require('path');
const axios = require('axios');

const KEY = (process.env.GOOGLE_PLACES_API_KEY || '').trim();
const OUT_PATH = path.resolve(__dirname, 'menu-test-urls.txt');

// Diverse Chicago seed list — known to span multiple website platforms.
// Edit or replace freely.
const DEFAULT_NAMES = [
  "Lou Malnati's Pizzeria, Chicago",
  "Girl & the Goat, Chicago",
  "Au Cheval, Chicago",
  "The Purple Pig, Chicago",
  "Pequod's Pizza, Chicago",
  "The Dearborn Tavern, Chicago",  // BentoBox — our baseline
  "Avec, Chicago",
  "Monteverde, Chicago",
  "Kasama, Chicago",
  "Daisies, Chicago",
  "Boka, Chicago",
  "Big Star, Chicago",
  "Smyth, Chicago",
  "Spiaggia, Chicago",
  "Honey Butter Fried Chicken, Chicago",
];

function parseArgs(argv) {
  if (argv.length === 0) return DEFAULT_NAMES.slice();
  const names = [];
  for (const a of argv) {
    const abs = path.resolve(process.cwd(), a);
    if (fs.existsSync(abs) && fs.statSync(abs).isFile()) {
      const lines = fs.readFileSync(abs, 'utf-8').split('\n');
      for (const raw of lines) {
        const line = raw.trim();
        if (line && !line.startsWith('#')) names.push(line);
      }
    } else {
      names.push(a);
    }
  }
  return names;
}

async function resolveOne(name) {
  try {
    const findUrl = 'https://maps.googleapis.com/maps/api/place/findplacefromtext/json';
    const r1 = await axios.get(findUrl, {
      params: { input: name, inputtype: 'textquery', fields: 'place_id,name', key: KEY },
      timeout: 8000,
    });
    const place = r1.data?.candidates?.[0];
    if (!place?.place_id) return { name, website: null, error: 'no place found' };

    const detailsUrl = 'https://maps.googleapis.com/maps/api/place/details/json';
    const r2 = await axios.get(detailsUrl, {
      params: { place_id: place.place_id, fields: 'name,website', key: KEY },
      timeout: 8000,
    });
    const website = r2.data?.result?.website || null;
    const resolvedName = r2.data?.result?.name || name;
    return { name: resolvedName, website, error: website ? null : 'no website on place' };
  } catch (e) {
    return { name, website: null, error: e?.message || String(e) };
  }
}

/** Expand a homepage URL to candidate menu URLs. */
function candidatesFor(homepage) {
  const base = homepage.replace(/\/$/, '');
  return [base, `${base}/menu`, `${base}/menus`];
}

async function main() {
  if (!KEY) {
    console.error('GOOGLE_PLACES_API_KEY is not set in server/.env');
    console.error('Either set it locally or paste menu URLs directly into:');
    console.error('  ' + OUT_PATH);
    process.exit(1);
  }

  const names = parseArgs(process.argv.slice(2));
  console.log(`Resolving ${names.length} restaurant name(s) via Google Places…\n`);

  const lines = [];
  lines.push('# Generated by seedMenuTestUrls.js — feel free to add or remove.');
  lines.push('# Each restaurant gets 3 URL candidates: homepage, /menu, /menus.');
  lines.push('# The test harness will report which one parses.');
  lines.push('');

  for (let i = 0; i < names.length; i++) {
    const name = names[i];
    process.stdout.write(`[${i + 1}/${names.length}] ${name} … `);
    const r = await resolveOne(name);
    if (!r.website) {
      console.log(`skipped (${r.error})`);
      lines.push(`# ${r.name} — ${r.error}`);
      lines.push('');
      continue;
    }
    console.log(r.website);
    lines.push(`# ${r.name}`);
    for (const url of candidatesFor(r.website)) lines.push(url);
    lines.push('');
  }

  fs.writeFileSync(OUT_PATH, lines.join('\n'));
  console.log(`\nWrote ${OUT_PATH}`);
  console.log('Next:');
  console.log('  node server/scripts/testMenuExtraction.js server/scripts/menu-test-urls.txt');
}

main().catch((e) => {
  console.error('seed crashed:', e);
  process.exit(1);
});
