/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/discover`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/log-visit`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/tonight`; params?: Router.UnknownInputParams; } | { pathname: `/tonight/join`; params?: Router.UnknownInputParams; } | { pathname: `/tonight/matches`; params?: Router.UnknownInputParams; } | { pathname: `/tonight/swipe`; params?: Router.UnknownInputParams; } | { pathname: `/restaurant/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/discover`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/log-visit`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/tonight`; params?: Router.UnknownOutputParams; } | { pathname: `/tonight/join`; params?: Router.UnknownOutputParams; } | { pathname: `/tonight/matches`; params?: Router.UnknownOutputParams; } | { pathname: `/tonight/swipe`; params?: Router.UnknownOutputParams; } | { pathname: `/restaurant/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/discover${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/log-visit${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/tonight${`?${string}` | `#${string}` | ''}` | `/tonight/join${`?${string}` | `#${string}` | ''}` | `/tonight/matches${`?${string}` | `#${string}` | ''}` | `/tonight/swipe${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/discover`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/log-visit`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/tonight`; params?: Router.UnknownInputParams; } | { pathname: `/tonight/join`; params?: Router.UnknownInputParams; } | { pathname: `/tonight/matches`; params?: Router.UnknownInputParams; } | { pathname: `/tonight/swipe`; params?: Router.UnknownInputParams; } | `/restaurant/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/restaurant/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
